### ISSUE TITLE
Design a Page

### ISSUE THREAD

**Issue by vishnaka-dasanayaka** [vishnaka-dasanayaka/SLTMS#1]
Please design a form for teachers in order to add their course content. when they select one of their courses the form should prompt. following attributes should be their.

1. relavent month
2. area to upload files (.pdf)
3. title of the lesson
4. small description
5. Average Duration
6. other required informatiom

Add this design to the figma and the upload a .txt file including figma link to the repo

**Comment by ashan1998** [comment]
[FIGMAlink.txt](https://github.com/vishnaka-dasanayaka/SLTMS/files/12224920/FIGMAlink.txt)
